{"name": "test_login_username_empty2[test_info0]", "status": "broken", "statusDetails": {"message": "TypeError: find_element() argument after * must be an iterable, not NoneType", "trace": "self = <test_cases.test_001_login.TestLogin object at 0x000002368701BE48>\ntest_info = {'expected': '请输入密码!', 'pwd': '', 'user': 'ceshi01'}\nget_browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"850163391a35e2b3f9a9dc3fa49eed6c\")>\n\n    @pytest.mark.parametrize('test_info', login_data_error2)\n    @allure.story(\"密码为空\")\n    def test_login_username_empty2(self, test_info, get_browser):\n        print(\"------执行登录密码为空测试用例------\")\n        driver = get_browser\n        expected = test_info['expected']\n>       LoginPage(driver).login(test_info[\"user\"], test_info[\"pwd\"])\n\ntest_001_login.py:37: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\pages\\login_page.py:42: in login\n    self.move_click(btn_elem)\n..\\common\\base_page.py:161: in move_click\n    ele= self.wait_clickable_element(locator)\n..\\common\\base_page.py:82: in wait_clickable_element\n    EC.element_to_be_clickable(locator)\nC:\\Python37\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:71: in until\n    value = method(self._driver)\nC:\\Python37\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py:297: in __call__\n    element = visibility_of_element_located(self.locator)(driver)\nC:\\Python37\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py:128: in __call__\n    return _element_if_visible(_find_element(driver, self.locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"850163391a35e2b3f9a9dc3fa49eed6c\")>\nby = None\n\n    def _find_element(driver, by):\n        \"\"\"Looks up an element. Logs and re-raises ``WebDriverException``\n        if thrown.\"\"\"\n        try:\n>           return driver.find_element(*by)\nE           TypeError: find_element() argument after * must be an iterable, not NoneType\n\nC:\\Python37\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py:411: TypeError"}, "attachments": [{"name": "log", "source": "6c7a8328-c278-4fa0-8d00-00f23736a4ef-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "test_info", "value": "{'user': 'ceshi01', 'pwd': '', 'expected': '请输入密码!'}"}], "start": 1600343680290, "stop": 1600343689499, "uuid": "5666d4ff-28cb-4a4b-a441-ed2d118ecd7a", "historyId": "d313ac42ce0148469f42a835f93a5a6a", "testCaseId": "7706f36e1018e82971782f24504c9efe", "fullName": "test_cases.test_001_login.TestLogin#test_login_username_empty2", "labels": [{"name": "story", "value": "密码为空"}, {"name": "parentSuite", "value": "test_cases"}, {"name": "suite", "value": "test_001_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-G986QGRS"}, {"name": "thread", "value": "22432-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.test_001_login"}]}