{"name": "test_login_username_empty[test_info0]", "status": "broken", "statusDetails": {"message": "TypeError: find_element() argument after * must be an iterable, not NoneType", "trace": "self = <test_cases.test_001_login.TestLogin object at 0x000002368701B148>\ntest_info = {'expected': '请输入用户名!', 'pwd': '', 'user': ''}\nget_browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"5e9abbf4156775819623d2f418d43c33\")>\n\n    @pytest.mark.parametrize('test_info', login_data_error)\n    @allure.story(\"用户名密码为空\")\n    def test_login_username_empty(self, test_info, get_browser):\n        print(\"-----执行登录用户名密码为空测试用例-----\")\n        driver = get_browser\n        expected = test_info['expected']\n>       LoginPage(driver).login(test_info[\"user\"], test_info[\"pwd\"])\n\ntest_001_login.py:18: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\pages\\login_page.py:42: in login\n    self.move_click(btn_elem)\n..\\common\\base_page.py:161: in move_click\n    ele= self.wait_clickable_element(locator)\n..\\common\\base_page.py:82: in wait_clickable_element\n    EC.element_to_be_clickable(locator)\nC:\\Python37\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:71: in until\n    value = method(self._driver)\nC:\\Python37\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py:297: in __call__\n    element = visibility_of_element_located(self.locator)(driver)\nC:\\Python37\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py:128: in __call__\n    return _element_if_visible(_find_element(driver, self.locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"5e9abbf4156775819623d2f418d43c33\")>\nby = None\n\n    def _find_element(driver, by):\n        \"\"\"Looks up an element. Logs and re-raises ``WebDriverException``\n        if thrown.\"\"\"\n        try:\n>           return driver.find_element(*by)\nE           TypeError: find_element() argument after * must be an iterable, not NoneType\n\nC:\\Python37\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py:411: TypeError"}, "attachments": [{"name": "log", "source": "a2b21081-88a9-4bf5-9cbb-b1c1b4a704cc-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "test_info", "value": "{'user': '', 'pwd': '', 'expected': '请输入用户名!'}"}], "start": 1600343658274, "stop": 1600343667019, "uuid": "b7f24def-8dd5-4e82-9105-7c7bc08e71ca", "historyId": "ee7cbe9c00c89a3fed88a7c391b3f2df", "testCaseId": "5613f2d1a0651959484942007a1e287f", "fullName": "test_cases.test_001_login.TestLogin#test_login_username_empty", "labels": [{"name": "story", "value": "用户名密码为空"}, {"name": "parentSuite", "value": "test_cases"}, {"name": "suite", "value": "test_001_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-G986QGRS"}, {"name": "thread", "value": "22432-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.test_001_login"}]}